version: '3'
services:
  server1:
    image: server1
    build: ./server1
    ports:
      - 3009:3009
    environment:
      - PORT=3009
      - REDIS_URL=redis://bun-redis:6379
    volumes:
      - ./app:/app
    depends_on:
      - bun-redis
  server2:
    image: server2
    build: ./server2
    ports:
      - 3010:3010
    environment:
      - PORT=3010
      - REDIS_URL=redis://bun-redis:6379
    volumes:
      - ./app:/app
    depends_on:
      - bun-redis
  bun-redis:
    container_name: bun-redis
    image: redis
    ports:
      - "6378:6379"
    volumes:
      - "./data/redis:/data"
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16